### ISSUE TITLE
categories aren't obvious - add a glossary?

### ISSUE THREAD

**Issue by malcomio** [Capgemini/grade-ladder#29]
unless you're a role-playing geek, terms like `Dex` and `Fel` are meaningless

create a glossary, and link to it

**Comment by malcomio** [comment]
are these categories even necessary? don't the terms like "Technical Skills" make them superfluous?

**Comment by glawrence** [comment]
I was just having that exact thought, personally I have no idea what they are or mean and it adds confusion, unless I missed something
