### ISSUE TITLE
GradeLadder pages not working

### ISSUE THREAD

**Issue by ChrisJBurns** [Capgemini/grade-ladder#38]
When navigating to the GradeLadder grade pages. We get PageNotFound errors: https://capgemini.gitbooks.io/grade-ladder/content/A%20Grades/A01-ApprenticeSoftwareEngineer/

Additionally, when curling the page we get the following:

```bash
$ curl -I GET https://capgemini.gitbooks.io/grade-ladder/content/A%20Grades/A01-ApprenticeSoftwareEngineer/
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 23 Sep 2020 19:42:17 GMT
Content-Type: text/html; charset=utf-8
Connection: close
Expires: Wed, 23 Sep 2020 19:52:17 GMT
Cache-Control: max-age=600
X-Frame-Options: DENY

HTTP/2 404
date: Wed, 23 Sep 2020 19:42:17 GMT
content-type: text/html
content-length: 8185
set-cookie: __cfduid=dadae8608f8a7ad43c103e64ae5d66c831600890137; expires=Fri, 23-Oct-20 19:42:17 GMT; path=/; domain=.gitbooks.io; HttpOnly; SameSite=Lax
cf-request-id: 055e1604dc000007126baa4200000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 5d76bf816bbb0712-LHR
```

**Comment by glawrence** [comment]
@broomyocymru seems the PDF is also not working, any ideas how we fix this please?

**Comment by broomyocymru** [comment]
Looks like gitbooks site has been updated and I don't have access to the legacy 'org' to migrate the gitbook. Will have a more detailed look when I get chance.

**Comment by broomyocymru** [comment]
Legacy orgs were decommissioned in April. As a work around I've imported the existing capgemini/grade-ladder repo into a personal space at https://broomyocymru.gitbook.io/grade-ladder/ which should be enough for eoy activities while we work out how to resolve the permissions.

**Comment by glawrence** [comment]
Thanks Ant, much appreciated

**Comment by broomyocymru** [comment]
> @broomyocymru seems the PDF is also not working, any ideas how we fix this please?

PDF generation is now a paid for 'Feature' , think we should prob review an alternative location to host.

**Comment by nighk** [comment]
@broomyocymru How about using something similar to our Engineering Blog: https://pages.github.com/

There are various ways we can make a PDF from markdown, there is a VS Code plugin for it: https://marketplace.visualstudio.com/items?itemName=yzane.markdown-pdf, or there is a node library: https://www.npmjs.com/package/markdown-pdf. I'm sure there will be libraries for the other formats we publish it by as well if needed ;-)

I am happy to help look into it sometime if you like? Or chat about alternative ideas?

**Comment by malcomio** [comment]
@nighk looks like this is now at https://capgemini.github.io/grade-ladder/ - I guess we can close this issue, and create specific issues for any other tweaks needed?

**Comment by malcomio** [comment]
do we even need a PDF version? I'd say having it available on GitHub pages should be enough

**Comment by nighk** [comment]
@malcomio I agree I don't think a PDF version is needed for now, if it ever is we can easily generate one from the grade md files ;-)
