### ISSUE TITLE
Page Title Typo and Problem with About/Main page

### ISSUE THREAD

**Issue by glawrence** [Capgemini/grade-ladder#51]
I have just been reading [Grade Ladder | Cagemini OSCE Grade Ladder](https://capgemini.github.io/grade-ladder/) and noticed the last paragraph says this:

> We’re still working on definitions for our grades 9 and above, and will continue to evolve our existing definitions. We encourage everyone to provide feedback.

However we have now got a page for A9.

Oh and further more, every page title says "Cagemini OSCE Grade Ladder" which contains a typo!

**Comment by malcomio** [comment]
the site title has been fixed in #53 

see #54 for the last paragraph

**Comment by glawrence** [comment]
Great, thanks @malcomio much appreciated
